### ISSUE TITLE
Nan to Nothing

### ISSUE THREAD

**Issue by GheorgheP** [jlmorgan/node-lodash-fantasy#25]
At the moment expressions like hits will return a `Just(Nan)`:

```js
Maybe.from(Number('not a number')) //Just(NaN)
```

Does it make sense to place the `NaN` type as empty type like `undefined` an `null`?

**Comment by jlmorgan** [comment]
The intent for `Maybe` is that is represents the absence of _value_. From the [Mozilla](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) documentation:

> The global `NaN` property is a value representing Not-A-Number.

It is because of this that false-like things are not included in the `Maybe` because they are values.

That aside, I'm in the moment of a large refactor of this code and one of the key methods is `Maybe#filter` which would allow you to reject things like `NaN` doing something like this:

```javascript
const F = require("lodash/fp");

Maybe.just("not a number")
  .map(Number)
  .filter(F.negate(Number.isNaN));
// => Nothing()
```

**Comment by GheorgheP** [comment]
Thank you for explanation. I created `MaybeNumber` by extending the `Maybe` class.
